-- Community Intake v1
-- Supabase becomes the canonical store for Scent Requests and Journal Feedback.
-- Production storefront traffic is not switched by this migration alone.
-- Google Sheets remains the mirror/audit system during rollout.

create table if not exists public.scent_requests (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  fragrance text not null,
  fragrance_normalized text not null,
  language text not null default '',
  page text not null default '',
  source text not null default 'scent_request',
  device_id text not null,
  mirror_status text not null default 'pending',
  mirror_synced_at timestamptz,
  mirror_error text,
  constraint scent_requests_fragrance_length check (char_length(fragrance) between 1 and 240),
  constraint scent_requests_device_length check (char_length(device_id) between 1 and 200),
  constraint scent_requests_language_length check (char_length(language) <= 12),
  constraint scent_requests_page_length check (char_length(page) <= 500),
  constraint scent_requests_source check (source = 'scent_request'),
  constraint scent_requests_mirror_status check (mirror_status in ('pending','synced','failed','legacy_import'))
);

create index if not exists scent_requests_created_at_idx
  on public.scent_requests (created_at desc);
create index if not exists scent_requests_device_created_idx
  on public.scent_requests (device_id, created_at desc);
create index if not exists scent_requests_device_fragrance_idx
  on public.scent_requests (device_id, fragrance_normalized, created_at desc);
create index if not exists scent_requests_fragrance_idx
  on public.scent_requests (fragrance_normalized, created_at desc);

create table if not exists public.journal_feedback (
  id bigint generated by default as identity primary key,
  feedback_id text not null unique,
  device_id text not null,
  article text not null,
  article_title text not null default '',
  vote text not null,
  note text not null default '',
  language text not null default '',
  page text not null default '',
  source text not null default 'journal_feedback',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  mirror_status text not null default 'pending',
  mirror_synced_at timestamptz,
  mirror_error text,
  constraint journal_feedback_vote check (vote in ('up','down')),
  constraint journal_feedback_article_length check (char_length(article) between 1 and 200),
  constraint journal_feedback_device_length check (char_length(device_id) between 1 and 200),
  constraint journal_feedback_note_length check (char_length(note) <= 2000),
  constraint journal_feedback_title_length check (char_length(article_title) <= 500),
  constraint journal_feedback_language_length check (char_length(language) <= 12),
  constraint journal_feedback_page_length check (char_length(page) <= 500),
  constraint journal_feedback_source check (source = 'journal_feedback'),
  constraint journal_feedback_mirror_status check (mirror_status in ('pending','synced','failed','legacy_import')),
  constraint journal_feedback_device_article_unique unique (device_id, article)
);

create index if not exists journal_feedback_updated_at_idx
  on public.journal_feedback (updated_at desc);
create index if not exists journal_feedback_article_idx
  on public.journal_feedback (article, updated_at desc);

alter table public.scent_requests enable row level security;
alter table public.journal_feedback enable row level security;

revoke all on table public.scent_requests from anon, authenticated;
revoke all on table public.journal_feedback from anon, authenticated;

create or replace function public.normalize_scent_request_name(p_value text)
returns text
language plpgsql
immutable
set search_path = ''
as $function$
declare
  v_text text := lower(trim(coalesce(p_value,'')));
  v_token text;
  v_tokens text[] := array[]::text[];
begin
  -- Match the storefront normalization closely without requiring extensions.
  v_text := translate(
    v_text,
    'àáâãäåāăąçćčďđèéêëēĕėęěìíîïīĭįñńňòóôõöøōŏőřśšşťùúûüūŭůűųýÿžźż',
    'aaaaaaaaacccddeeeeeeeeeiiiiiiinnnooooooooorssstuuuuuuuuuuyyzzz'
  );
  v_text := replace(v_text, '&', ' and ');
  v_text := regexp_replace(v_text, '[^a-z0-9]+', ' ', 'g');

  foreach v_token in array regexp_split_to_array(trim(v_text), '[[:space:]]+')
  loop
    if v_token <> '' and v_token not in (
      'eau','de','parfum','perfume','edp','edt','cologne','extrait','extract','spray'
    ) then
      v_tokens := array_append(v_tokens, v_token);
    end if;
  end loop;

  return trim(array_to_string(v_tokens, ' '));
end;
$function$;

create or replace function public.submit_scent_request(
  p_fragrance text,
  p_language text default '',
  p_page text default '',
  p_device_id text default ''
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_fragrance text := trim(coalesce(p_fragrance,''));
  v_device_id text := trim(coalesce(p_device_id,''));
  v_language text := left(trim(coalesce(p_language,'')),12);
  v_page text := left(trim(coalesce(p_page,'')),500);
  v_normalized text;
  v_now timestamptz := now();
  v_latest_same timestamptz;
  v_recent_count integer := 0;
  v_oldest_recent timestamptz;
  v_remaining interval;
  v_remaining_days integer;
  v_remaining_hours integer;
  v_id bigint;
begin
  if v_fragrance = '' or char_length(v_fragrance) > 240 then
    return jsonb_build_object('status','error','message','Invalid fragrance');
  end if;
  if v_device_id = '' or char_length(v_device_id) > 200 then
    return jsonb_build_object('status','error','message','Invalid deviceId');
  end if;

  v_normalized := public.normalize_scent_request_name(v_fragrance);
  if v_normalized = '' then
    return jsonb_build_object('status','error','message','Invalid fragrance');
  end if;

  -- Serialize votes per device so fast parallel clicks cannot bypass limits.
  perform pg_advisory_xact_lock(hashtextextended(v_device_id, 0));

  select max(created_at)
  into v_latest_same
  from public.scent_requests
  where device_id = v_device_id
    and source = 'scent_request'
    and fragrance_normalized = v_normalized;

  if v_latest_same is not null and v_latest_same > v_now - interval '3 days' then
    v_remaining := (v_latest_same + interval '3 days') - v_now;
    v_remaining_days := greatest(1, ceil(extract(epoch from v_remaining) / 86400.0)::integer);
    return jsonb_build_object(
      'status','blocked',
      'type','scent_request',
      'blockReason','same_fragrance',
      'message','Same fragrance cooldown active',
      'remainingDays',v_remaining_days
    );
  end if;

  select count(*), min(created_at)
  into v_recent_count, v_oldest_recent
  from public.scent_requests
  where device_id = v_device_id
    and source = 'scent_request'
    and created_at > v_now - interval '24 hours';

  if v_recent_count >= 3 then
    v_remaining := (v_oldest_recent + interval '24 hours') - v_now;
    v_remaining_hours := greatest(1, ceil(extract(epoch from v_remaining) / 3600.0)::integer);
    return jsonb_build_object(
      'status','blocked',
      'type','scent_request',
      'blockReason','daily_limit',
      'message','Daily scent request limit reached',
      'remainingHours',v_remaining_hours
    );
  end if;

  insert into public.scent_requests (
    created_at, fragrance, fragrance_normalized, language, page, source, device_id
  ) values (
    v_now, v_fragrance, v_normalized, v_language, v_page, 'scent_request', v_device_id
  )
  returning id into v_id;

  return jsonb_build_object(
    'status','ok',
    'type','scent_request',
    'id',v_id
  );
end;
$function$;

create or replace function public.upsert_journal_feedback(
  p_article text,
  p_article_title text,
  p_vote text,
  p_note text,
  p_operation text,
  p_language text,
  p_page text,
  p_device_id text,
  p_feedback_id text default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_article text := trim(coalesce(p_article,''));
  v_device_id text := trim(coalesce(p_device_id,''));
  v_vote text := lower(trim(coalesce(p_vote,'')));
  v_note text := trim(coalesce(p_note,''));
  v_operation text := lower(trim(coalesce(p_operation,'')));
  v_feedback_id text;
  v_existing public.journal_feedback%rowtype;
  v_row public.journal_feedback%rowtype;
  v_action text;
begin
  if v_operation = '' then
    v_operation := case when v_note <> '' then 'note' else 'vote' end;
  end if;
  v_feedback_id := 'journal_' || v_device_id || '_' || v_article;

  if v_article = '' or char_length(v_article) > 200
     or v_device_id = '' or char_length(v_device_id) > 200
     or v_vote not in ('up','down')
     or v_operation not in ('vote','note')
     or (v_operation = 'note' and (v_note = '' or char_length(v_note) > 2000))
     or (p_feedback_id is not null and p_feedback_id <> v_feedback_id)
  then
    return jsonb_build_object('status','error','message','Invalid journal feedback');
  end if;

  perform pg_advisory_xact_lock(hashtextextended(v_feedback_id, 0));

  select * into v_existing
  from public.journal_feedback
  where feedback_id = v_feedback_id
  for update;

  if found then
    update public.journal_feedback
    set
      article_title = left(coalesce(p_article_title,''),500),
      vote = v_vote,
      note = case when v_operation = 'note' then v_note else note end,
      language = left(coalesce(p_language,''),12),
      page = left(coalesce(p_page,''),500),
      source = 'journal_feedback',
      updated_at = now(),
      mirror_status = 'pending',
      mirror_synced_at = null,
      mirror_error = null
    where feedback_id = v_feedback_id
    returning * into v_row;
    v_action := 'updated';
  else
    insert into public.journal_feedback (
      feedback_id, device_id, article, article_title, vote, note,
      language, page, source, created_at, updated_at
    ) values (
      v_feedback_id, v_device_id, v_article, left(coalesce(p_article_title,''),500),
      v_vote, case when v_operation = 'note' then v_note else '' end,
      left(coalesce(p_language,''),12), left(coalesce(p_page,''),500),
      'journal_feedback', now(), now()
    )
    returning * into v_row;
    v_action := 'created';
  end if;

  return jsonb_build_object(
    'status','ok',
    'type','journal',
    'feedbackId',v_feedback_id,
    'operation',v_operation,
    'action',v_action,
    'id',v_row.id
  );
end;
$function$;

create or replace function public.get_public_scent_request_totals()
returns jsonb
language sql
security definer
set search_path = ''
as $function$
  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'name', x.name,
        'votes', x.votes,
        'firstSeen', x.first_seen
      )
      order by x.votes desc, x.name asc
    ),
    '[]'::jsonb
  )
  from (
    select
      (array_agg(fragrance order by created_at asc))[1] as name,
      count(*)::integer as votes,
      min(created_at) as first_seen
    from public.scent_requests
    where source = 'scent_request'
    group by fragrance_normalized
  ) x;
$function$;

create or replace function public.get_control_center_community_intake()
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_uid uuid := auth.uid();
  v_scent jsonb;
  v_feedback jsonb;
  v_articles jsonb;
begin
  if v_uid is null then raise exception 'AUTH_REQUIRED' using errcode='42501'; end if;
  if not exists (select 1 from public.admin_users a where a.user_id=v_uid) then
    raise exception 'ADMIN_REQUIRED' using errcode='42501';
  end if;

  select coalesce(jsonb_agg(to_jsonb(s) order by s.votes desc, s.last_requested_at desc),'[]'::jsonb)
  into v_scent
  from (
    select
      fragrance_normalized,
      (array_agg(fragrance order by created_at asc))[1] as fragrance,
      count(*)::integer as votes,
      count(distinct device_id)::integer as unique_devices,
      min(created_at) as first_requested_at,
      max(created_at) as last_requested_at,
      count(*) filter (where mirror_status='failed')::integer as mirror_failures
    from public.scent_requests
    group by fragrance_normalized
  ) s;

  select coalesce(jsonb_agg(to_jsonb(f) order by f.updated_at desc),'[]'::jsonb)
  into v_feedback
  from (
    select id, feedback_id, device_id, article, article_title, vote, note,
      language, page, created_at, updated_at, mirror_status
    from public.journal_feedback
    order by updated_at desc
    limit 500
  ) f;

  select coalesce(jsonb_agg(to_jsonb(a) order by a.total_votes desc, a.latest_at desc),'[]'::jsonb)
  into v_articles
  from (
    select
      article,
      (array_agg(article_title order by updated_at desc))[1] as article_title,
      count(*)::integer as total_votes,
      count(*) filter (where vote='up')::integer as positive,
      count(*) filter (where vote='down')::integer as negative,
      count(*) filter (where note <> '')::integer as comments,
      min(created_at) as first_at,
      max(updated_at) as latest_at
    from public.journal_feedback
    group by article
  ) a;

  return jsonb_build_object(
    'scent_requests', v_scent,
    'journal_feedback', v_feedback,
    'journal_articles', v_articles,
    'canonical_source', 'supabase',
    'backup_source', 'google_sheets'
  );
end;
$function$;

grant execute on function public.submit_scent_request(text,text,text,text) to anon, authenticated;
grant execute on function public.upsert_journal_feedback(text,text,text,text,text,text,text,text,text) to anon, authenticated;
grant execute on function public.get_public_scent_request_totals() to anon, authenticated;
grant execute on function public.get_control_center_community_intake() to authenticated;
